### ISSUE TITLE
Update Form

### ISSUE THREAD

**Issue by nhindman23** [bio-xyz/bioacc-manifesto#1]
- Changed placeholder to Albert Einstein in each field
- Added "(Optional") to the Email and Affiliation prompt
- Corrected typo in the visibility message and added below all fields

<img width="843" alt="image" src="https://github.com/bio-xyz/bioacc-manifesto/assets/53524917/9e1a471b-5450-4482-b8e1-988ba1c9f2a7">

**Comment by elmariachi111** [comment]
updated that & also addressed form validation (enabling / disabling the submission button)
