### ISSUE TITLE
on mobile safari browser & chrome (Iphone XR): text and repost X modal overflow the edges of the screen after user starts to fill the form 

### ISSUE THREAD

**Issue by Leo-bioxyz** [bio-xyz/bioacc-manifesto#11]
![Screenshot 2024-07-02 at 13 20 35](https://github.com/bio-xyz/bioacc-manifesto/assets/154607986/f497fcb4-3c33-4c93-a0ee-03778029dea6)

First the page looks great and the paddings are applied correctly. After I start filling the form, the overflow starts and i can move the page left and right and the text overflow appears.

**Comment by elmariachi111** [comment]
should be gone now.

**Comment by Leo-bioxyz** [comment]
perfect, works great!
