### ISSUE TITLE
Design Updates + Updates to signing flow

### ISSUE THREAD

**Issue by nhindman23** [bio-xyz/bioacc-manifesto#12]
@elmariachi111 
See figma here for latest design: https://www.figma.com/design/QWSmPupYwqtCDJ1DN08pbu/bio%2Facc?node-id=55-221

Changes:

- [x] Make heart larger
- [x] Check all headers are 24px, subheaders are 18px.
- [x] left align main bio/acc manifesto header
- [x] set body text to "justify" - https://www.w3schools.com/cssref/css3_pr_text-justify.php
- [x] Update bio/acc trinity image
- [x] Update Bio singularity image
- [x] Add light grey dividers between bottom sections
- [x] Center the bio/acc logo above thanks
- [x] Update styling of 'signers' list
- [x] Update styling of 'sign' form
- [x] Add inline repost on twitter step after form submit

Last note is that you'll see in the figma the two images were removed from the body text.
Paul is coming up with two images he'd like to use to replace those images. So if you want to hold off on removing them and just swap them out with the new images once we have them, that would work.

**Comment by elmariachi111** [comment]
Added most of them -> https://bioacc-manifesto-ouodder9l-bio-xyz.vercel.app/

- if you mean that "diagram" image, that's just an svg; used the most recent version by Vincent but haven't touched it at all. If I'd use the raster image, I'd guess it's nearly unreadable.

- wdym with "inline repost on twitter step"? That's how it looks like: 
![image](https://github.com/bio-xyz/bioacc-manifesto/assets/1344649/2f31fe90-b640-4315-99d2-3dd89ed45809)

Embedded tweets don't allow other inline interactions than the ones shown -> https://developer.x.com/en/docs/twitter-for-websites/embedded-tweets/overview

@nhindman23
