### ISSUE TITLE
"sign at bottom of page" button - apply paddings as per the new design 

### ISSUE THREAD

**Issue by Leo-bioxyz** [bio-xyz/bioacc-manifesto#13]
Just flagging this as not mentioned in the Design update ticket: 

The button in the top section has a reduced width in the new design file it seems. Adapt the padding please. 

https://www.figma.com/design/QWSmPupYwqtCDJ1DN08pbu/bio%2Facc?node-id=55-221

**Comment by elmariachi111** [comment]
they look pretty similar to the document.
