### ISSUE TITLE
update trinity image

### ISSUE THREAD

**Issue by nhindman23** [bio-xyz/bioacc-manifesto#18]
new image here: https://cdn.discordapp.com/attachments/1253985360279633980/1258063888520446043/image.png?ex=6686aecc&is=66855d4c&hm=0fce08717497725542e2bbcb15e16319fa167ed20e50282b6845ea427b5c6f71&

**Comment by elmariachi111** [comment]
think this is done, no? 🤔 @nhindman23 
<img width="768" alt="image" src="https://github.com/user-attachments/assets/4b92c8d2-64f0-49f9-a87c-12e11aef4daa">

**Comment by nhindman23** [comment]
yes done
