### ISSUE TITLE
Add image before bio/acc principles

### ISSUE THREAD

**Issue by nhindman23** [bio-xyz/bioacc-manifesto#19]
![image 9](https://github.com/user-attachments/assets/7ecfdcbb-8c70-4ed0-85e7-43c522ca7ae8)

^ add this image to the text in-line, right before "bio/acc principles"

<img width="932" alt="image" src="https://github.com/user-attachments/assets/21a98110-75ce-45f5-a1ad-062edc78fc16">

@elmariachi111

**Comment by elmariachi111** [comment]
voila https://bioacc-manifesto.vercel.app/
