### ISSUE TITLE
Updates to signing flow

### ISSUE THREAD

**Issue by nhindman23** [bio-xyz/bioacc-manifesto#26]
Update the signing flow to make it clearer that sharing on X is required and also add an optional input for wallet address (optional) which we can use for future airdrops

Wallet address should be sent to prive google sheet where all other form data is sent, and NOT shown in the user's final signature that will be manually added by us

@elmariachi111 

<img width="580" alt="image" src="https://github.com/user-attachments/assets/1cb455f2-9e89-4c7a-be2f-c36b4633fdbd">

**Comment by elmariachi111** [comment]
give me some inspiration for the success message, too. Think we can increase the "repost" button size / repeat the call to action differently

<img width="875" alt="image" src="https://github.com/user-attachments/assets/36ac59d3-9bed-4b30-8c1f-decb1399b722">

**Comment by elmariachi111** [comment]
fixed by #27
