### ISSUE TITLE
Change font color of chapter headings 

### ISSUE THREAD

**Issue by Leo-bioxyz** [bio-xyz/bioacc-manifesto#9]
Please change the font-color of the three chapter headings "Bio Singularity" ; "bio/acc principles" ; "The bio/acc trinity"
to "hsl(var(--primary))" (same as button color and any of of the neon green used on the site).

**Comment by nhindman23** [comment]
@elmariachi111 hold off on this for a moment, Si is testing in design and then we'll decide

**Comment by Leo-bioxyz** [comment]
deleting this, not applicable anymore
